#' View All Linked payment Methods.
#'
#' @name pymt_methods
#'
#' @description TBD
#'
#' @param api.key Mandatory character value. This is the API key as generated by GDAX. Typically a 32 character value.
#' @param secret Mandatory character value. This is the API secret as generated by GDAX. Typically a 88 character value.
#' @param passphrase THE URL component for the API. Default to "/accounts". Typically a 11 character value.
#'
#' @return A named list.
#'
#' @examples
#' \dontrun{
#' pmt_methods(api.key = your_key, secret = your_api_secret, passphrase = your_api_pass)
#' }
#'
#' @export


pymt_methods <- function(api.key,
                         secret,
                         passphrase) {
  #get url extension----
  req.url = "/payment-methods"

  #get method----
  method = "GET"

  #fetch response----
  payment_methods <- auth(
    method = method,
    req.url = req.url,
    api.key = api.key,
    secret = secret,
    passphrase = passphrase
  )

  #return----
  return(payment_methods)
}
